### ISSUE TITLE
define testbed: HW and VMs

### ISSUE THREAD

**Issue by konstan** [nuvlaedge/validation#2]
- [ ] Create a documentation page with the list of devices. Should go here https://github.com/nuvlaedge/validation/tree/main/docs

List of hardware (and VMs) and their location [preliminary list - to be completed]:

- VM at Exoscale (exists)
- RaspberryPi 4 (exists)
- RaspberryPi 3B+
- HPE GL10 ?
- OnLogic Mini [ML100G-10](https://www.onlogic.com/eu-en/ml100g-10/)
- OnLogic Standard [model?](?)
- Onlogic [HX500](https://www.onlogic.com/hx500/) (to be ordered) 
- RevolutionPi [(RevPi Connect S(E) or RevPi Connect+)](https://revolutionpi.com/revpi-connect/)
- Exoscale VM
- Ekinops OVP
- Ekinops ONE2560
- Ekinops ONE5G

**Comment by ignacio-penas** [comment]
Captured in https://github.com/SixSq/tasklist/issues/2576
